const LOGIN = 'LOGIN';
const REGISTER = 'REGISTER';
const CREATE = 'CREATE';
const FETCH_ALL = 'FETCH_ALL';
const LOADING = 'LOADING';
const REFRESH = 'REFRESH';

export {LOGIN, REGISTER, CREATE, FETCH_ALL, LOADING, REFRESH};
